### ISSUE TITLE
Upgrade pydap.handlers.pcic requirement

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp_util#4]
`pydap.handlers.pcic` is pegged at v0.0.4 in the [requirements.txt](https://github.com/pacificclimate/pdp_util/blob/master/requirements.txt#L12), but we've tagged [several versions](https://github.com/pacificclimate/pydap.handlers.pcic/releases) since then.

Upgrade the requirement (to at least 0.0.7) and ensure that all of the tests pass.

**Comment by CBMasri** [comment]
Okay, I had a look and the reason the [xls_response test](https://github.com/pacificclimate/pdp/blob/8c81071a6488e73df80e90cbce766415b980fbb3/tests/test_functional.py#L93-L107) fails using the latest pydap.handlers.pcic package (0.0.7) is because of the addition of a new global attribute "[elevation](https://github.com/pacificclimate/pydap.handlers.pcic/commit/f1204cb5e05a988617fbcdb02095212ef88ebf38#diff-657ea16c90a57e73ddad13cd40be92c9R130)". The assertions in the test case are performed against these global values using a numerical index, so adding the extra attribute threw everything off by one.

**Comment by jameshiebert** [comment]
OK, good to know. Thanks for the detective work. Just to clarify, does that mean that all of the pdp_util tests will pass using `pydap.handlers.pcic` v0.7.0? If so, then I guess we just want to bump the requirement version (and release a new version of `pdp_util`) in this package, and then update the tests and the requirements.txt in `pdp`.

**Comment by CBMasri** [comment]
All except one passes: [test_auth](https://github.com/pacificclimate/pdp_util/blob/b5b0a15eae5cca967918c75e880a15a34ec1721a/tests/test_auth.py#L61) redirect returns `401 Unauthorized`. It looks like there have been some changes to OpenID since the test case was written, perhaps the link has changed?

**Comment by jameshiebert** [comment]
Hrm yeah. OpenID [has been dead for a while](https://github.com/pacificclimate/pdp/issues/24). Feel free to [mark that test as skipped](http://doc.pytest.org/en/latest/skipping.html#marking-a-test-function-to-be-skipped).
